import { geistMono, geistSans } from '@/fonts';
import './globals.css';
import NextAuthProvider from '@/provider/NextAuthProvider';
import Script from 'next/script';

export const metadata = {
  title: 'Next.js Custom Template',
  description: 'Generated by Shadow Monarch',
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html
        lang="en"
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <head>
          <Script
            id="theme-initializer"
            dangerouslySetInnerHTML={{
              __html: `
              try {
                const theme = localStorage.getItem('theme') || 'dark';
                document.documentElement.setAttribute('data-theme', theme);
              } catch (_) {}
            `,
            }}
          />
        </head>
        <body
          suppressHydrationWarning
          className="min-h-full flex flex-col bg-base-100 text-base-content transition-colors duration-200"
        >
          {children}
        </body>
      </html>
    </NextAuthProvider>
  );
}
